### ISSUE TITLE
Can't run "hugo new" because empty archetypes/default.md file

### ISSUE THREAD

**Issue by fleebzz** [rakuishi/hugo-zen#2]
I set in my config file :

```
theme = "hugo-zen"
```

And now when I run `hugo new <something_new>` I have :

```
ERROR: 2016/02/18 Error processing archetype file: <path_to_my_project>/themes/hugo-zen/archetypes/default.md
ERROR: 2016/02/18 Unable to Cast <nil> to map[string]interface{}
```

To be able to run the command I had to remove the file `default.md`. Now it uses the default one from Hugo and I can create new content.

Is it ok to think we should remove this file from the project ? And maybe just keep an empty `.gitkeep` file in the `archetypes` directory if needed.

Thanks

**Comment by rakuishi** [comment]
Thank you for your reporting!

I removed `default.md` from hugo-zen, and pushed it.

**Comment by fleebzz** [comment]
Thank you ! :smiley:
